# Generated by Django 4.0.1 on 2022-02-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournamnets',
            new_name='Tournaments',
        ),
    ]
