# Generated by Django 4.0.1 on 2022-01-30 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournamnets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('START', 'START'), ('SPORT', 'SPORT'), ('CHALLENGER', 'CHALLENGER')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('prestige', models.IntegerField()),
                ('surface', models.CharField(choices=[('CLAY', 'CLAY'), ('HARD', 'HARD'), ('ARTIFICAL_TURF', 'ARTIFICAL_TURF'), ('GRASS', 'GRASS')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CONSOLIDATED', 'CONSOLIDATED'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20)),
                ('price', models.IntegerField()),
                ('user', models.ManyToManyField(blank=True, related_name='competitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
