# Generated by Django 4.0.1 on 2022-02-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_rename_tournamnets_tournaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='competitors',
        ),
    ]
