# Generated by Django 4.0.1 on 2022-02-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_registration_cancelled_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'tournament')},
        ),
    ]
