# Generated by Django 4.0.1 on 2022-02-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='tournaments.tournaments'),
        ),
    ]
