# Generated by Django 4.0.1 on 2022-02-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_registration_options_tournamentgroup_setstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgroup',
            name='name',
            field=models.CharField(default='Group1', max_length=50),
            preserve_default=False,
        ),
    ]
