# Generated by Django 4.0.1 on 2022-02-21 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournamentgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournaments'),
        ),
        migrations.AlterField(
            model_name='setstat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='set_stats', to='tournaments.tournamentgroup'),
        ),
        migrations.AlterField(
            model_name='tournamentgroup',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_goroup', to='tournaments.tournaments'),
        ),
    ]
