# Generated by Django 4.0.1 on 2022-02-24 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_registration_tournament_alter_setstat_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setstat',
            name='score_p1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
        migrations.AlterField(
            model_name='setstat',
            name='score_p2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
        migrations.CreateModel(
            name='EliminationDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(4, 4), (8, 8), (16, 16), (32, 32)])),
                ('type_of', models.CharField(choices=[('MAIN', 'MAIN'), ('SECONDARY', 'SECONDARY')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentgroup')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
