# Generated by Django 4.0.1 on 2022-02-24 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_setstat_score_p1_alter_setstat_score_p2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setstat',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_stats', to='tournaments.tournamentgroup'),
        ),
        migrations.AlterField(
            model_name='setstat',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournaments'),
        ),
        migrations.CreateModel(
            name='EliminationDrawMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_of', models.IntegerField()),
                ('match', models.IntegerField()),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.eliminationdraw')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='setstat',
            name='draw_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_stats', to='tournaments.eliminationdrawmatch'),
        ),
    ]
