# Generated by Django 4.0.1 on 2022-02-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_remove_eliminationdraw_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setstat',
            name='draw_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_stats', to='tournaments.eliminationdrawmatch'),
        ),
        migrations.AlterField(
            model_name='setstat',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_stats', to='tournaments.tournamentgroup'),
        ),
    ]
