# Generated by Django 4.0.1 on 2022-02-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_alter_setstat_draw_match_alter_setstat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setstat',
            name='draw_match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_stat', to='tournaments.eliminationdrawmatch'),
        ),
    ]
