# Generated by Django 4.0.1 on 2022-02-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_alter_setstat_draw_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminationdrawmatch',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.eliminationdraw'),
        ),
    ]
