# Generated by Django 4.0.1 on 2022-02-28 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_alter_eliminationdrawmatch_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminationdrawmatch',
            name='draw',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.eliminationdraw'),
        ),
        migrations.AlterField(
            model_name='eliminationdrawmatch',
            name='match',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='GroupScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_won', models.PositiveIntegerField(blank=True, null=True)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tournaments.tournamentgroup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_scores', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_scores', to='tournaments.tournaments')),
            ],
        ),
    ]
